### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.grangerhub.Tremulous#3]
It would be great if the Tremulous Flatpak could be verified.

Here are more details about verified apps: https://flathub.org/about

It can be done after @cengique has the correct push rights to this repo (see flathub/com.grangerhub.Tremulous#19).

**Comment by AsciiWolf** [comment]
@cengique Any chance this Flatpak could be verified? :-) Verification will most likely be required in the future and some Linux distributions (for example, Linux Mint) are already starting to hide unverified Flatpak apps in their software centres.

**Comment by cengique** [comment]
> @cengique Any chance this Flatpak could be verified? :-) Verification will most likely be required in the future and some Linux distributions (for example, Linux Mint) are already starting to hide unverified Flatpak apps in their software centres.

Hi! @AsciiWolf yes, I can proceed to verify it. However, I don't see it show up in my Developer Portal when I log into Flathub with my Github account. Any advice?

**Comment by AsciiWolf** [comment]
That's very strange. You do have push rights to this repository so the Verification option should be there when opening the [Tremulous](https://flathub.org/apps/manage/com.grangerhub.Tremulous) page on your Developer Portal.

![screenshot](https://github.com/flathub/com.grangerhub.Tremulous/assets/2339930/3195f9cd-0d57-427e-947a-5bf660199354)

**Comment by cengique** [comment]
> That's very strange. You do have push rights to this repository so the Verification option should be there when opening the [Tremulous](https://flathub.org/apps/manage/com.grangerhub.Tremulous) page on your Developer Portal.

Ok, you're right it does show up there! I was looking under my settings and it showed as blank for some reason. Actually, now it shows up in settings as well, so I'm not sure what changed.

New problem: We have lost the `grangerhub.com` domain and there is only the forum hosted under the new `grangerhub.org` domain. Let me ask someone if I can get access to the grangerhub.org domain.

**Comment by AsciiWolf** [comment]
> We have lost the grangerhub.com domain and there is only the forum hosted under the new grangerhub.org domain.

Oops, that may be a problem and it may require moving this Flatpak to `org.grangerhub.Tremulous`. :-/

**Comment by AsciiWolf** [comment]
It should now be possible to verify the Flatpak.

**Comment by AsciiWolf** [comment]
@cengique Ping. :-)

**Comment by cengique** [comment]
@AsciiWolf sorry, I've been traveling. Will check this soon!

**Comment by AsciiWolf** [comment]
@cengique Any update?

**Comment by cengique** [comment]
Yes, I'm back and planning to work on it soon! There was also some more progress by other members on the website, which is good.

**Comment by cengique** [comment]
@AsciiWolf I'm again getting a blank list on Flathub:
![image](https://github.com/user-attachments/assets/e20ea33f-6ae4-4f3c-ae92-08481b0010b4)

I'm assuming nothing changed? If so, I'll keep on trying until I can log in properly.

**Comment by AsciiWolf** [comment]
Because it looks like you do not have push right to this Git repo for some reason.

**edit:** Looks like [bbhtt](https://github.com/bbhtt) already added you. You just have to accept the invite.

**Comment by barthalion** [comment]
Yeah. When you have, click "refresh" button and physically refresh the tab after few minutes.

**Comment by cengique** [comment]
@barthalion thank you, it did show! I also selected the new login system verification. It didn't have any steps, but it does now say "Your app is currently verified by your login @grangerhub with your account on GitHub". However, it didn't reflect on the app page yet.

**Comment by AsciiWolf** [comment]
It now displays as verified. Yay! :-)
